### ISSUE TITLE
add python-dotenv

### ISSUE THREAD

**Issue by fynnfluegge** [fynnfluegge/codeqai#4]
The OpenAI and Azure API Key should be isolated in the pipx installation. The user should be prompted to enter the necessary environment variables if not available in the isolated environment. These variables should be stored in an `.env` file. 
Use https://github.com/theskumar/python-dotenv

**Comment by bhargavnova** [comment]
you can assign this to me?

**Comment by fynnfluegge** [comment]
Sure, thanks for picking this up @bhargavnova !

**Comment by bhargavnova** [comment]
Hi @fynnfluegge , I add coded the module,
Just let me know where should I put that in your repo code.
that would be easy for you.

`script_name : env_loader.py` has funciton `env_loader()`

**Comment by fynnfluegge** [comment]
> Hi @fynnfluegge , I add coded the module,
> 
> Just let me know where should I put that in your repo code.
> 
> that would be easy for you.
> 
> 
> 
> `script_name : env_loader.py` has funciton `env_loader()`

Perfect, I think app.py is fine. You can raise a PR and I will take a look later 🙌

**Comment by bhargavnova** [comment]
done : )
