### ISSUE TITLE
Support for reStructuredText, and Markdown

### ISSUE THREAD

**Issue by jasgeo75** [fynnfluegge/codeqai#5]
Treesitter was a brilliant addition.  Any chance we might see support added for reStructuredText (rst) and Markdown (md) files?

**Comment by fynnfluegge** [comment]
> Treesitter was a brilliant addition.  Any chance we might see support added for reStructuredText (rst) and Markdown (md) files?

Sure, will add C#, Cpp and C support very soon. Then rst, md and yaml with its treesitter grammars. 🙌

Feel free to raise PR if you are faster haha 😄

**Comment by fynnfluegge** [comment]
@jasgeo75 any suggestion how to incorporate treesitter with markdown or rst? I have the feeling textsplitters by langchain are sufficient here, wdyt?

**Comment by jasgeo75** [comment]
@fynnfluegge The reStructuredText and Markdown parsers for [Treesitter](https://tree-sitter.github.io/tree-sitter/) appear to be for Rust.  Langchain textsplitters are probably the way to go.
